language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  api_key:
    secure: HcTCKA+nNuRctSFxbHKK8yjJn2pBsxQBsaGltBdz/oBW3PE9vKiqe6c4vS12CxrYy1rR9gCA0HJSOtncW9dZBaXrsacnf0L8bRo85gmZcNs2TJfINQY0ZsHLNyTmk5KMVOOZGUEopNWTW4KqHArJS4OlSAijIsMa5HIHHyxSlZRTYJiFHkJ8ug/enmr7+6JaiCdFdh2flo7ZaCm9UdsRI9YqO7U38bTJZdr4615DnRO/K3ZxjH7iFM7CY3rcc5D9QnlWQMh7aCjaCmOCsRl+KrT34GPmKDixVMcwyeyY0Zkhx5DEt9bLsToBJw42PkbQC02d/qM4uxCAxKOdk3aXT5tHbbUWLXP6SNKS/EW+D4p0JsVBTzRZiK4CNQuliSTJlEKJLVkMdx5GOrW58DgqnSWTnfhmsdZY38+pd0AAYHZCbfkd8oI/xcw4FeBkzxbW5+SOh70nxNCI76bmDohQZSG1Td9BKa4OwkbcIvET1Q1Y+NRBIhcDIxQUzqxUNN9Qn+2Qxnn4r31skD3D7J6SUf+bTyXq60lQaRa/BXStfR4USE5KgiLHMwSKDZRwTEZUpFLy+Pdv0nvnX7ZYajpffs2b89Qnx8yh9bVh39069ODYQNUbjoJaa4jdFsYPbNvluHtfb47hFsli6ZSEoAEvgYnp3fd3sFMFgRIQhmvz77U=
