language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: EAlHjcEiSJehHai6eeH3+Naha/GMJTahFoB+xa+fYNnEqRQzxiPlRyywTiHauYSaNzuRYcoTOIuqVLR/qZ+1/wk1FjkeduDvSxZH3e/dgOXZTAYdsnfK2PWqi80qJWa0AJ+76u2KjADfb37b5B1c2vQbmKfIxgBizacHRDCg4kU8XM2+YtVw8YpF03QO35H4q0cwmXyrbckzvxXm9UJ+k9dVYaRecw3YZx1HRgYNZlBLTz6dC+Cz4Gb15YEga6iVaRA4VfEwPAAzGWfkFLSv5FJiZLEQ4bj56u4c22zNjPZwe4yDGRn2ED4fWXu3EqgIgql1zPkYQnek8hi2OYb34uKJ+8z+oWt1nLPpLT2v01c7rwCq7DwRBdFCKwqgzfIKUW1TG77y3FGkiS/tl0taGLQqAxiENoFKf+pagbByVDjAIuZwDvN7gvBHU1L0X+wqc2Wgmkqya/9BofNumCjOhHpNiVR2MoB3QiQyj4FcMmF0NgwcgIKanTfQj8kSSzEeT3Fn7UnVCX7189Ge1ub4ScUZ8Tx27zqX/aCvhgwrpzIUzuK8RwZTOPOR2PFM+kd7K76IjuvUnFxI09SF+ejtJiq55jIZEiQwy2orleiwZZ/X2jngVo9npX8+pWwxfDxNHtsF7ncOYM7QAqet/MnJ04OMgo2gkBgBGe5TyY9WDHo=
    app:
      master: book-basket-staging
      production: book-basket-fe