language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: UGtXP6aVEZp9HPKjEhintu7emZkOmU8L1Uz+nV22U4fsCO89jv11tdWjrqKOwJ5Oaz409NYSLoLUfJsoKiXOIGIdyObrAYmBj/sqSVQB9+jx7eLGs26C7FmpfWmHdHftiS5rutlUvuxstSUSQCPX8vS2OjhdNmiqjYCASDQE/6zqSbgQZgbbwyTPMmtDNmqtnSSx6Uai5gDREZqQdq7MOBK6YZf3IBqVk71ltqVVXjiE8FJJmf9qUEE7wo8/lX38iY3GSio67TGPTnDvOQR7/Ljr8Mt4cwn+81EsJMhB7ajFRf8dXHaNihcRX7NM5Nz8WBTOeZDbbYOocIrfdcKAiBoRrlvNSB37bFbaJ0nW9jPpL3wNVHS6i9JQLy++R7v83dOyBfSwCyWfwLEgmzdXEeKCmNdVsdWMlTq/D1DmWN/nfT37bvvCbCOCmdn4A/CCYibbEpKadM4NtkVZzOo/Jb1Q1qj97YX+hwIWN7ZCCwA1103Nw8QLLvYBqGYJwlWg9uKE2R2+aeGrJLqIWRaessA76M33ZIJtrnxxVD+cslZPygqUnNfOKQT3h6NiexRDoetO7Er2GsCbArqlV1/XebT5tWg/a0H5neTlvLPdaeVMIFq7XSWVCKhiBgp5BLAosTYsUm52F2Wtyd8+kHZhyjbBDaQaE+QVl9QNDz0tb3E=
    app:
      master: book-basket-staging
      production: book-basket-fe